<div class="row">

<script>
    $(function() {
        $('#datepicker').datepicker({
            dateFormat: "dd-mm-yy",
            maxDate: +0,
            minDate: '30-06-2012',
            onSelect: function(dateText, inst) {
                values = $("#slider" ).slider("option", "values");
                createPlot(dateText, values[0], values[1]);
            $('.jqplot-title').html('kWh Verbruik voor ' + $('#datepicker').val() + ' '+ timeNotation(values[0]) + '-' + timeNotation(values[1]));
            }
        });
    });
</script>
<div style="width: 100%">
    <div class="demo" style="display: inline-block; width: 18%;">
    Datum: <input type="text" id="datepicker" value='<?php echo date('d-m-Y', time()); ?>'>
    </div>
    <span id="startTimeText">00:00</span>
    <div style='width: 5px; display: inline-block'></div>
    <div id="slider" style="width:70%; display: inline-block"></div>
    <div style='width: 5px; display: inline-block'></div>
    <span id="endTimeText">24:00</span>
</div>
<div id="chartdiv" style="height:500px;"></div>
<script>
// The url for our json data
var jsonurl = "./data";
  
$(document).ready(function(){
    createPlot('<?php echo $this->shownDate; ?>', 0 ,<?php echo $this->nextHour; ?>);

    $( "#slider" ).slider({ 
        range: true,
        min: 0,
        max: 2400,
        values: [0,2400],
        step: 100,
        stop: function(event, ui) {
            //console.log(ui.values[1]);
            createPlot($('#datepicker').val(), ui.values[0] , ui.values[1]);
            $("#startTimeText").html(timeNotation(ui.values[0]));
            $("#endTimeText").html(timeNotation(ui.values[1]));
            //$('.jqplot-title').html('kWh Verbruik voor ' + $('#datepicker').val() + ' '+ timeNotation(ui.values[0]) + '-' + timeNotation(ui.values[1]));
        }
    });
});
function redraw(jsonurl) {
    createPlot('<?php echo $this->shownDate; ?>', 0 ,2400);
}

function createPlot(datum, startTime, endTime) {
    $('#chartdiv').html('');
    
    var jsonurl = "./data";
    var ajaxDataRenderer = function(url, plot, options) {
        var ret = null;
        $.ajax({
            async: false,
            url: url,
            data: { fromDate: datum + 'T' + timeNotation(startTime), toDate: datum + 'T' + timeNotation(endTime) },
            dataType:'json',
            success: function(data) {
                $("#maxTableCell").html(data[1]['max'] + ' Watt');
                $("#avgTableCell").html(data[1]['avg'] + ' Watt');
                $("#sumTableCell").html(data[1]['sum'] + ' kWh');
                ret = data[0];
            }
        });
        
        return ret;
    };
    if (endTime == 2400) {
        endTime = 2359;
    }
    endTime = pad(endTime, 4);
    startTime = pad(startTime, 4);

    datum = datum.substr(6,4) + '-' + datum.substr(3,2) + '-' + datum.substr(0,2);

    var plot1b = $.jqplot('chartdiv', jsonurl,{
        title: 'kWh Verbruik voor <?php echo $this->shownDate ?>',
        dataRenderer: ajaxDataRenderer,
        dataRendererOptions: { 
            unusedOptionalUrl: jsonurl
        },
        series:[{
            lineWidth:4,
            //markerOptions:{style:'square'},
            renderer:$.jqplot.BarRenderer
        }],
        seriesDefaults: {
            fill: true,
            rendererOptions: {fillToZero: true}
        },
        axesDefaults: {
            tickRenderer: $.jqplot.CanvasAxisTickRenderer ,
            tickOptions: {
                fontSize: '10pt',
                angle: -30
            }
        },
        axes: {
            xaxis: {
                label: 'Tijd',
                renderer:$.jqplot.DateAxisRenderer,
                tickOptions:{
                    showGridline: false,
                    formatString:'%H:%M'
                    //tickInterval: "1 hour",
                },
                min: datum + ' ' + timeNotation(startTime),
                max: datum + ' ' + timeNotation(endTime),
                showTicks: true
            },
            yaxis:{
                min:0,
                label:'Watt',
                labelRenderer: $.jqplot.CanvasAxisLabelRenderer,
                labelOptions: {
                    angle: 90
                }
//                max:<?php echo $max; ?>,
//                numberTicks: 11
            }
        },
        highlighter: {
            show: true,
            sizeAdjust: 7.5
        },
        cursor: {
            show: true,
            zoom: true
        }
    });
}
</script>
<table>
    <tr>
        <th>Totaal:</th>
        <td id="sumTableCell"></td>
    </tr>
    <tr>
        <th>Max:</th>
        <td id="maxTableCell"></td>
    </tr>
    <tr>
        <th>Gemiddeld:</th>
        <td id="avgTableCell"></td>
    </tr>
</table>
    
    
</div>
